apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namespace-configuration-operator

bases:
  - ../../base
  - ../../../installplan-approver/base

resources:
  - namespace.yaml
  - operator-group.yaml
