apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mta-web-console
    application: mta-web-console
    xpaas: 1.3.2
    manager: kube-controller-manager
  name: mta-web-console-postgresql-claim
  namespace: app-migration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
