apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
    app.kubernetes.io/component: maven-m2-pvc
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/part-of: jenkins
  name: maven-m2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
